### PR TITLE
feat: added add to likes and watch-later feature

### PR DESCRIPTION
**Pull request by AnjaliDeshwani**
Below functionalities are added -

- Added add to likes and remove from likes
- Added add to history and remove from history
- Added add to watch-later and remove from watch-later

### CODE REVIEW

**Review by lomesshh — APPROVED** [review]
code looks clean
all functionalities are working as expected
UI also looks great

looks good to merge

**Review by Pratik1005 — APPROVED** [review]
Functionality working properly, good code structure
Just a suggestion: use delete icon for remove from history option

**Comment by AnjaliDeshwani** [comment]
> Functionality working properly, good code structure Just a suggestion: use delete icon for remove from history option

Thanks for the suggestion Pratik, I have updated it now.

**Comment by AnjaliDeshwani** [comment]
> code looks clean all functionalities are working as expected UI also looks great
> 
> looks good to merge

 Thanks for reviewing.

**Pull request merged**
