### PR TITLE
feat: added toast and  theme

### PR DESCRIPTION
**Pull request by AnjaliDeshwani**
- Added toast
- Added dark and light mode
- Added navlink in sidebar and made some minor changes in css classes

### CODE REVIEW

**Review by saketkum11 — APPROVED** [review]
- clean code
- much easy to undrestand
- UI Is great
- one thing I have created playlist but could not add video in theParticular playlist.

**Comment by AnjaliDeshwani** [comment]
> * clean code
> * much easy to undrestand
> * UI Is great
> * one thing I have created playlist but could not add video in theParticular playlist.

@saketkum11 thanks for reviewing, I just checked user must be login to add videos in playlist or watchlater.
Thanks for pointing this out, I will redirect user to login page.

**Review by muskaanshah — APPROVED** [review]
UI looks clean
There's a bug - the one which Saket pointed out

**Comment by AnjaliDeshwani** [comment]
> UI looks clean There's a bug - the one which Saket pointed out

Thanks for reviewing, I have fixed it now.

**Pull request merged**
